mex PlattSigmoid.cpp CXXFLAGS="\$CXXFLAGS -fopenmp" LDFLAGS="\$LDFLAGS ...
    -fopenmp"
mex ComputeProbabilityMapShortestPath.cpp CXXFLAGS="\$CXXFLAGS -fopenmp ...
     -O3" LDFLAGS="\$LDFLAGS -fopenmp"
