close all
clear all

%% Testing
mask = '/media/data/steerableFilters2D/neurons/n7/2/N7_2_mask.jpg';
nPts = 100;
maskIgnore = '/media/data/steerableFilters2D/neurons/n7/2/mask_ignore.jpg';

    % '2/frangi_2.jpg', ...
    % '2/meijeering_2.jpg', ...
    % '2/oof.jpg', ...
    % '2/l1.jpg', ...
    % 'coords/N7_order_2_radius_3_eOrdsInc_0_style_thin.jpg', ...
    % 'coords/N7_order_2_radius_5_eOrdsInc_0_style_thin.jpg', ...
    % 'coords/N7_order_2_radius_7_eOrdsInc_0_style_thin.jpg', ...
    % 'coords/N7_order_2_radius_9_eOrdsInc_0_style_thin.jpg', ...
    % 'coords/N7_order_2_radius_11_eOrdsInc_0_style_thin.jpg', ...


names = { ...
    '2/oof.jpg', ...
    '2/l1.jpg', ...
    '2/meijeering_2.jpg', ...
    'coords/N7_order_2_radius_7_eOrdsInc_0_style_thin.jpg', ...
        };

%% data harvesting
figure;
tpra = [];
fpra = [];
for i = 1:1:size(names,2)
    [tpr,fpr] = roc_from_images(['/media/data/steerableFilters2D/neurons/n7/' ...
                        names{i}], mask, nPts, maskIgnore);
    tpra = [tpra ; tpr'];
    fpra = [fpra ; fpr'];
end

%% plot the stuff
close all
plot(log10(fpra'), tpra')
title('Neurons Dataset')
xlabel('FPR')
ylabel('TPR')
set(findobj('Type','line'), 'LineWidth', 3);
legend(names, 'Location', 'NorthWest')
save2pdf('images/rocNeurons.pdf')
save('evaluationNeurons.mat')
