SET(GMODULE_FOUND 0)

INCLUDE(K3DFindPkgConfig)
PKG_CHECK_MODULES(GMODULE gmodule-2.0)

IF(GMODULE_FOUND)
	SET(GMODULE_INCLUDE_DIRS
		${GMODULE_INCLUDE_DIRS}
		)

	SET(GMODULE_LIB_DIRS
		${GMODULE_LIBRARY_DIRS}
		)

	SET(GMODULE_LIBS
		${GMODULE_LIBRARIES}
		)

	SET(GMODULE_FOUND 1)
ENDIF(GMODULE_FOUND)
