function trkSaveEssentialData(filename, D, Dlist, FILAMENTS, Soma, FrameMeasures, GlobalMeasures, timeSeq, tracks, trkSeq)

disp(['...saving essential information to ' filename]);
save(filename, 'NUC_INT_THRESH',...
     'D',... 
     'Dlist',...
     'FILAMENTS',...
     'Soma',...
     'FrameMeasures',...
     'GlobalMeasures',...
     'timeSeq',...
     'tracks',...
     'trkSeq');
