function trkSaveEssentialData(filename, D, Dlist, FIL, FILAMENTS, Soma, FrameMeasures, GlobalMeasures, timeSeq, tracks, trkSeq)

for i = 1:length(FIL)
    FIL{i} = int16(FIL{i});
end


disp(['...saving essential information to ' filename]);
save(filename, ...
     'D',... 
     'Dlist',...
     'FILAMENTS',...
     'FIL',...
     'Soma',...
     'FrameMeasures',...
     'GlobalMeasures',...
     'timeSeq',...
     'tracks',...
     'trkSeq');
