close all
clear all

%% Testing
mask = '/media/data/steerableFilters2D/drive/d22/d22_mask.jpg';
nPts = 50;
maskIgnore = '/media/data/steerableFilters2D/drive/d22/d22_training_mask_eroded.jpg';

    % '2/frangi_2.jpg', ...
    % '2/meijeering_2.jpg', ...
% names = { ...
    % 'coords/d22_order_4_radius_3_eOrdsInc_0_.jpg', ...
    % 'coords/d22_order_4_radius_5_eOrdsInc_0_.jpg', ...
    % 'coords/d22_order_4_radius_7_eOrdsInc_0_.jpg', ...
    % 'coords/d22_order_4_radius_9_eOrdsInc_0_.jpg', ...
    % 'coords/d22_order_4_radius_11_eOrdsInc_0_.jpg', ...
% }
    % 'coords/d22_order_4_radius_9_eOrdsInc_0_.jpg', ...
    
names = { ...
    'oof.jpg', ...
    'l1.jpg', ...
    'meijeering.jpg', ...
    'coords/d22_order_2_radius_9_eOrdsInc_0_.jpg', ...
        };

%% data harvesting
figure;
tpra = [];
fpra = [];
for i = 1:1:size(names,2)
    [tpr,fpr] = roc_from_images(['/media/data/steerableFilters2D/drive/d22/' ...
                        names{i}], mask, nPts, maskIgnore);
    tpra = [tpra ; tpr'];
    fpra = [fpra ; fpr'];
end

%% plot the stuff
plot(log10(fpra'), (tpra'))
title('Drive Dataset')
xlabel('FPR')
ylabel('TPR')
set(findobj('Type','line'), 'LineWidth', 3);
legend(names, 'Location', 'NorthWest')
save2pdf('images/rocDrive.pdf')
save('evaluationDrive.mat')