/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_ascEditor (void);
GtkWidget* create_ascEditControls (void);
GtkWidget* create_ascSelectShaders (void);
GtkWidget* create_ascEditControlsSelect (void);
