/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ascEditor (void)
{
  GtkWidget *ascEditor;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *New_Neuron;
  GtkWidget *open_neuron;
  GtkWidget *save_neuron;
  GtkWidget *save_as1;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *screenshot;
  GtkWidget *image1;
  GtkWidget *cut1;
  GtkWidget *copy1;
  GtkWidget *paste1;
  GtkWidget *delete1;
  GtkWidget *menuitem6;
  GtkWidget *menuitem6_menu;
  GtkWidget *editAsc;
  GtkWidget *menu_plugins;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about1;
  GtkWidget *hbox1;
  GtkWidget *drawing3D;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkObject *layer_XY_spin_adj;
  GtkWidget *layer_XY_spin;
  GtkWidget *view_entry;
  GtkWidget *cube_transparency;
  GtkWidget *draw_neuron;
  GtkWidget *draw_cube_toggle;
  GtkWidget *label6;
  GtkObject *layer_view_adj;
  GtkWidget *layer_view;
  GtkWidget *label4;
  GtkObject *cube_row_spin_adj;
  GtkWidget *cube_row_spin;
  GtkWidget *label3;
  GtkObject *cube_col_spin_adj;
  GtkWidget *cube_col_spin;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkObject *layerXZ_spin_adj;
  GtkWidget *layerXZ_spin;
  GtkObject *layer_YZ_spin_adj;
  GtkWidget *layer_YZ_spin;
  GtkWidget *get_matrix_button;
  GtkWidget *shaders;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  ascEditor = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (ascEditor, 1024, 700);
  gtk_window_set_title (GTK_WINDOW (ascEditor), _("neseg 1.0"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (ascEditor), vbox1);
  GTK_WIDGET_SET_FLAGS (vbox1, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (vbox1, GTK_CAN_DEFAULT);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  New_Neuron = gtk_image_menu_item_new_from_stock ("gtk-new", accel_group);
  gtk_widget_show (New_Neuron);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), New_Neuron);

  open_neuron = gtk_image_menu_item_new_from_stock ("gtk-open", accel_group);
  gtk_widget_show (open_neuron);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), open_neuron);

  save_neuron = gtk_image_menu_item_new_from_stock ("gtk-save", accel_group);
  gtk_widget_show (save_neuron);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save_neuron);

  save_as1 = gtk_image_menu_item_new_from_stock ("gtk-save-as", accel_group);
  gtk_widget_show (save_as1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), save_as1);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  screenshot = gtk_image_menu_item_new_with_mnemonic (_("Screenshot"));
  gtk_widget_show (screenshot);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), screenshot);

  image1 = gtk_image_new_from_stock ("gtk-media-record", GTK_ICON_SIZE_MENU);
  gtk_widget_show (image1);
  gtk_image_menu_item_set_image (GTK_IMAGE_MENU_ITEM (screenshot), image1);

  cut1 = gtk_image_menu_item_new_from_stock ("gtk-cut", accel_group);
  gtk_widget_show (cut1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), cut1);

  copy1 = gtk_image_menu_item_new_from_stock ("gtk-copy", accel_group);
  gtk_widget_show (copy1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), copy1);

  paste1 = gtk_image_menu_item_new_from_stock ("gtk-paste", accel_group);
  gtk_widget_show (paste1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), paste1);

  delete1 = gtk_image_menu_item_new_from_stock ("gtk-delete", accel_group);
  gtk_widget_show (delete1);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), delete1);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menuitem6_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menuitem6_menu);

  editAsc = gtk_menu_item_new_with_mnemonic (_("editAsc"));
  gtk_widget_show (editAsc);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), editAsc);

  menu_plugins = gtk_menu_item_new_with_mnemonic (_("_Plugins"));
  gtk_widget_show (menu_plugins);
  gtk_container_add (GTK_CONTAINER (menubar1), menu_plugins);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  drawing3D = gtk_drawing_area_new ();
  gtk_widget_show (drawing3D);
  gtk_box_pack_start (GTK_BOX (hbox1), drawing3D, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawing3D, 800, 600);
  GTK_WIDGET_SET_FLAGS (drawing3D, GTK_CAN_FOCUS);
  gtk_widget_set_events (drawing3D, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON1_MOTION_MASK | GDK_BUTTON2_MOTION_MASK | GDK_BUTTON3_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_FOCUS_CHANGE_MASK | GDK_STRUCTURE_MASK | GDK_PROPERTY_CHANGE_MASK | GDK_VISIBILITY_NOTIFY_MASK | GDK_PROXIMITY_IN_MASK | GDK_PROXIMITY_OUT_MASK);
  gtk_widget_set_extension_events (drawing3D, GDK_EXTENSION_EVENTS_ALL);
  gtk_widget_add_accelerator (drawing3D, "grab-focus", accel_group,
                              GDK_d, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  table1 = gtk_table_new (20, 2, TRUE);
  gtk_widget_show (table1);
  gtk_box_pack_end (GTK_BOX (hbox1), table1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (table1, 224, 600);

  label2 = gtk_label_new (_("Layer XY"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label1 = gtk_label_new (_("View"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  layer_XY_spin_adj = gtk_adjustment_new (1, 0, 500, 1, 10, 10);
  layer_XY_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layer_XY_spin_adj), 1, 0);
  gtk_widget_show (layer_XY_spin);
  gtk_table_attach (GTK_TABLE (table1), layer_XY_spin, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  view_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_show (view_entry);
  gtk_table_attach (GTK_TABLE (table1), view_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("3D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("XY"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("XZ"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("YZ"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("Combo"));

  cube_transparency = gtk_toggle_button_new_with_mnemonic (_("Cube Transparency"));
  gtk_widget_show (cube_transparency);
  gtk_table_attach (GTK_TABLE (table1), cube_transparency, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  draw_neuron = gtk_toggle_button_new_with_mnemonic (_("Draw Neuron"));
  gtk_widget_show (draw_neuron);
  gtk_table_attach (GTK_TABLE (table1), draw_neuron, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  draw_cube_toggle = gtk_toggle_button_new_with_mnemonic (_("Draw Cube"));
  gtk_widget_show (draw_cube_toggle);
  gtk_table_attach (GTK_TABLE (table1), draw_cube_toggle, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label6 = gtk_label_new (_("LayerSpanViewZ"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table1), label6, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  layer_view_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  layer_view = gtk_spin_button_new (GTK_ADJUSTMENT (layer_view_adj), 1, 0);
  gtk_widget_show (layer_view);
  gtk_table_attach (GTK_TABLE (table1), layer_view, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Cube Row"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cube_row_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  cube_row_spin = gtk_spin_button_new (GTK_ADJUSTMENT (cube_row_spin_adj), 1, 0);
  gtk_widget_show (cube_row_spin);
  gtk_table_attach (GTK_TABLE (table1), cube_row_spin, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new (_("Cube Col"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  cube_col_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  cube_col_spin = gtk_spin_button_new (GTK_ADJUSTMENT (cube_col_spin_adj), 1, 0);
  gtk_widget_show (cube_col_spin);
  gtk_table_attach (GTK_TABLE (table1), cube_col_spin, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new (_("Layer XZ"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label8 = gtk_label_new (_("Layer YZ"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  layerXZ_spin_adj = gtk_adjustment_new (0, 0, 512, 1, 10, 10);
  layerXZ_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layerXZ_spin_adj), 1, 0);
  gtk_widget_show (layerXZ_spin);
  gtk_table_attach (GTK_TABLE (table1), layerXZ_spin, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  layer_YZ_spin_adj = gtk_adjustment_new (0, 0, 512, 1, 10, 10);
  layer_YZ_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layer_YZ_spin_adj), 1, 0);
  gtk_widget_show (layer_YZ_spin);
  gtk_table_attach (GTK_TABLE (table1), layer_YZ_spin, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  get_matrix_button = gtk_button_new_with_mnemonic (_("Get_Matrix"));
  gtk_widget_show (get_matrix_button);
  gtk_table_attach (GTK_TABLE (table1), get_matrix_button, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  shaders = gtk_button_new_with_mnemonic (_("Shaders"));
  gtk_widget_show (shaders);
  gtk_table_attach (GTK_TABLE (table1), shaders, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) ascEditor, "destroy",
                    G_CALLBACK (on_ascEditor_destroy),
                    NULL);
  g_signal_connect ((gpointer) New_Neuron, "activate",
                    G_CALLBACK (on_new_neuron_activate),
                    NULL);
  g_signal_connect ((gpointer) open_neuron, "activate",
                    G_CALLBACK (on_open_neuron_activate),
                    NULL);
  g_signal_connect ((gpointer) save_neuron, "activate",
                    G_CALLBACK (on_save_neuron_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1, "activate",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) screenshot, "activate",
                    G_CALLBACK (on_screenshot_activate),
                    NULL);
  g_signal_connect ((gpointer) cut1, "activate",
                    G_CALLBACK (on_cut1_activate),
                    NULL);
  g_signal_connect ((gpointer) copy1, "activate",
                    G_CALLBACK (on_copy1_activate),
                    NULL);
  g_signal_connect ((gpointer) paste1, "activate",
                    G_CALLBACK (on_paste1_activate),
                    NULL);
  g_signal_connect ((gpointer) delete1, "activate",
                    G_CALLBACK (on_delete1_activate),
                    NULL);
  g_signal_connect ((gpointer) editAsc, "activate",
                    G_CALLBACK (on_editAsc_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_plugins, "activate",
                    G_CALLBACK (on_menu_plugins_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "button_press_event",
                    G_CALLBACK (on_drawing3D_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "configure_event",
                    G_CALLBACK (on_drawing3D_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "expose_event",
                    G_CALLBACK (on_drawing3D_expose_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "motion_notify_event",
                    G_CALLBACK (on_drawing3D_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "key_press_event",
                    G_CALLBACK (on_drawing3D_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "realize",
                    G_CALLBACK (on_drawing3D_realize),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "button_release_event",
                    G_CALLBACK (on_drawing3D_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "scroll_event",
                    G_CALLBACK (on_drawing3D_scroll_event),
                    NULL);
  g_signal_connect ((gpointer) layer_XY_spin, "value_changed",
                    G_CALLBACK (on_layer_XY_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) view_entry, "changed",
                    G_CALLBACK (on_view_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) cube_transparency, "toggled",
                    G_CALLBACK (on_cube_transparency_toggled),
                    NULL);
  g_signal_connect ((gpointer) draw_neuron, "toggled",
                    G_CALLBACK (on_draw_neuron_toggled),
                    NULL);
  g_signal_connect ((gpointer) draw_cube_toggle, "toggled",
                    G_CALLBACK (on_draw_cube_toggle_toggled),
                    NULL);
  g_signal_connect ((gpointer) layer_view, "value_changed",
                    G_CALLBACK (on_layer_view_value_changed),
                    NULL);
  g_signal_connect ((gpointer) cube_row_spin, "value_changed",
                    G_CALLBACK (on_cube_row_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) cube_col_spin, "value_changed",
                    G_CALLBACK (on_cube_col_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) layerXZ_spin, "value_changed",
                    G_CALLBACK (on_layerXZ_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) layer_YZ_spin, "value_changed",
                    G_CALLBACK (on_layer_YZ_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) get_matrix_button, "clicked",
                    G_CALLBACK (on_get_matrix_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) shaders, "clicked",
                    G_CALLBACK (on_shaders_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascEditor, ascEditor, "ascEditor");
  GLADE_HOOKUP_OBJECT (ascEditor, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (ascEditor, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (ascEditor, New_Neuron, "New_Neuron");
  GLADE_HOOKUP_OBJECT (ascEditor, open_neuron, "open_neuron");
  GLADE_HOOKUP_OBJECT (ascEditor, save_neuron, "save_neuron");
  GLADE_HOOKUP_OBJECT (ascEditor, save_as1, "save_as1");
  GLADE_HOOKUP_OBJECT (ascEditor, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (ascEditor, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (ascEditor, screenshot, "screenshot");
  GLADE_HOOKUP_OBJECT (ascEditor, image1, "image1");
  GLADE_HOOKUP_OBJECT (ascEditor, cut1, "cut1");
  GLADE_HOOKUP_OBJECT (ascEditor, copy1, "copy1");
  GLADE_HOOKUP_OBJECT (ascEditor, paste1, "paste1");
  GLADE_HOOKUP_OBJECT (ascEditor, delete1, "delete1");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem6_menu, "menuitem6_menu");
  GLADE_HOOKUP_OBJECT (ascEditor, editAsc, "editAsc");
  GLADE_HOOKUP_OBJECT (ascEditor, menu_plugins, "menu_plugins");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (ascEditor, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (ascEditor, about1, "about1");
  GLADE_HOOKUP_OBJECT (ascEditor, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ascEditor, drawing3D, "drawing3D");
  GLADE_HOOKUP_OBJECT (ascEditor, table1, "table1");
  GLADE_HOOKUP_OBJECT (ascEditor, label2, "label2");
  GLADE_HOOKUP_OBJECT (ascEditor, label1, "label1");
  GLADE_HOOKUP_OBJECT (ascEditor, layer_XY_spin, "layer_XY_spin");
  GLADE_HOOKUP_OBJECT (ascEditor, view_entry, "view_entry");
  GLADE_HOOKUP_OBJECT (ascEditor, cube_transparency, "cube_transparency");
  GLADE_HOOKUP_OBJECT (ascEditor, draw_neuron, "draw_neuron");
  GLADE_HOOKUP_OBJECT (ascEditor, draw_cube_toggle, "draw_cube_toggle");
  GLADE_HOOKUP_OBJECT (ascEditor, label6, "label6");
  GLADE_HOOKUP_OBJECT (ascEditor, layer_view, "layer_view");
  GLADE_HOOKUP_OBJECT (ascEditor, label4, "label4");
  GLADE_HOOKUP_OBJECT (ascEditor, cube_row_spin, "cube_row_spin");
  GLADE_HOOKUP_OBJECT (ascEditor, label3, "label3");
  GLADE_HOOKUP_OBJECT (ascEditor, cube_col_spin, "cube_col_spin");
  GLADE_HOOKUP_OBJECT (ascEditor, label7, "label7");
  GLADE_HOOKUP_OBJECT (ascEditor, label8, "label8");
  GLADE_HOOKUP_OBJECT (ascEditor, layerXZ_spin, "layerXZ_spin");
  GLADE_HOOKUP_OBJECT (ascEditor, layer_YZ_spin, "layer_YZ_spin");
  GLADE_HOOKUP_OBJECT (ascEditor, get_matrix_button, "get_matrix_button");
  GLADE_HOOKUP_OBJECT (ascEditor, shaders, "shaders");

  gtk_widget_grab_focus (vbox1);
  gtk_widget_grab_default (vbox1);
  gtk_window_add_accel_group (GTK_WINDOW (ascEditor), accel_group);

  return ascEditor;
}

GtkWidget*
create_ascEditControls (void)
{
  GtkWidget *ascEditControls;
  GtkWidget *table2;
  GtkWidget *new_dendrite_button;
  GtkWidget *branch_button;
  GtkWidget *Erase_Point;
  GtkWidget *continue_segment_button;
  GtkWidget *delete_segment;
  GtkWidget *label5;
  GtkWidget *release_asc_action;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *select_point;
  GtkWidget *recursive_offset_closer_point;
  GtkWidget *recursive_offset_selected_point;
  GtkWidget *move_selected_point;
  GtkWidget *move_closer_point;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label9;
  GtkObject *ascEditor_width_adj;
  GtkWidget *ascEditor_width;
  GtkWidget *delete_segment_from_point;
  GtkWidget *label22;

  ascEditControls = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascEditControls), _("ascEditor"));

  table2 = gtk_table_new (15, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (ascEditControls), table2);

  new_dendrite_button = gtk_button_new_with_mnemonic (_("New Dendrite"));
  gtk_widget_show (new_dendrite_button);
  gtk_table_attach (GTK_TABLE (table2), new_dendrite_button, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  branch_button = gtk_button_new_with_mnemonic (_("New Branch"));
  gtk_widget_show (branch_button);
  gtk_table_attach (GTK_TABLE (table2), branch_button, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  Erase_Point = gtk_button_new_with_mnemonic (_("Erase Point"));
  gtk_widget_show (Erase_Point);
  gtk_table_attach (GTK_TABLE (table2), Erase_Point, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  continue_segment_button = gtk_button_new_with_mnemonic (_("Continue Segment"));
  gtk_widget_show (continue_segment_button);
  gtk_table_attach (GTK_TABLE (table2), continue_segment_button, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  delete_segment = gtk_button_new_with_mnemonic (_("Delete Segment"));
  gtk_widget_show (delete_segment);
  gtk_table_attach (GTK_TABLE (table2), delete_segment, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("ASC Creation"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  release_asc_action = gtk_button_new_with_mnemonic (_("noAction"));
  gtk_widget_show (release_asc_action);
  gtk_table_attach (GTK_TABLE (table2), release_asc_action, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("e"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new (_("w"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("r"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("t"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("g"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("b\n"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Asc Modification"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  select_point = gtk_button_new_with_mnemonic (_("Select Point"));
  gtk_widget_show (select_point);
  gtk_table_attach (GTK_TABLE (table2), select_point, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  recursive_offset_closer_point = gtk_button_new_with_mnemonic (_("Recursive Offset Closer Point"));
  gtk_widget_show (recursive_offset_closer_point);
  gtk_table_attach (GTK_TABLE (table2), recursive_offset_closer_point, 0, 1, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  recursive_offset_selected_point = gtk_button_new_with_mnemonic (_("Recursive Offet Selected Point"));
  gtk_widget_show (recursive_offset_selected_point);
  gtk_table_attach (GTK_TABLE (table2), recursive_offset_selected_point, 0, 1, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  move_selected_point = gtk_button_new_with_mnemonic (_("Move Selected Point"));
  gtk_widget_show (move_selected_point);
  gtk_table_attach (GTK_TABLE (table2), move_selected_point, 0, 1, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  move_closer_point = gtk_button_new_with_mnemonic (_("Move Closer Point"));
  gtk_widget_show (move_closer_point);
  gtk_table_attach (GTK_TABLE (table2), move_closer_point, 0, 1, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("z"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 1, 2, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("f"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 1, 2, 10, 11,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("x"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 1, 2, 11, 12,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("v"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 1, 2, 12, 13,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("c"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 1, 2, 13, 14,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label9 = gtk_label_new (_("Width"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 14, 15,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  ascEditor_width_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  ascEditor_width = gtk_spin_button_new (GTK_ADJUSTMENT (ascEditor_width_adj), 0.25, 0);
  gtk_widget_show (ascEditor_width);
  gtk_table_attach (GTK_TABLE (table2), ascEditor_width, 1, 2, 14, 15,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  delete_segment_from_point = gtk_button_new_with_mnemonic (_("Delete Segment From Point"));
  gtk_widget_show (delete_segment_from_point);
  gtk_table_attach (GTK_TABLE (table2), delete_segment_from_point, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label22 = gtk_label_new (_("h\n"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  g_signal_connect ((gpointer) new_dendrite_button, "clicked",
                    G_CALLBACK (on_new_dendrite_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) branch_button, "clicked",
                    G_CALLBACK (on_branch_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) Erase_Point, "clicked",
                    G_CALLBACK (on_Erase_Point_clicked),
                    NULL);
  g_signal_connect ((gpointer) continue_segment_button, "clicked",
                    G_CALLBACK (on_continue_segment_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete_segment, "clicked",
                    G_CALLBACK (on_delete_segment_clicked),
                    NULL);
  g_signal_connect ((gpointer) release_asc_action, "clicked",
                    G_CALLBACK (on_release_asc_action_clicked),
                    NULL);
  g_signal_connect ((gpointer) select_point, "clicked",
                    G_CALLBACK (on_select_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) recursive_offset_closer_point, "clicked",
                    G_CALLBACK (on_recursive_offset_closer_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) recursive_offset_selected_point, "clicked",
                    G_CALLBACK (on_recursive_offset_selected_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) move_selected_point, "clicked",
                    G_CALLBACK (on_move_selected_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) move_closer_point, "clicked",
                    G_CALLBACK (on_move_closer_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) ascEditor_width, "value_changed",
                    G_CALLBACK (on_ascEditor_width_value_changed),
                    NULL);
  g_signal_connect ((gpointer) delete_segment_from_point, "clicked",
                    G_CALLBACK (on_delete_segment_from_point_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascEditControls, ascEditControls, "ascEditControls");
  GLADE_HOOKUP_OBJECT (ascEditControls, table2, "table2");
  GLADE_HOOKUP_OBJECT (ascEditControls, new_dendrite_button, "new_dendrite_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, branch_button, "branch_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, Erase_Point, "Erase_Point");
  GLADE_HOOKUP_OBJECT (ascEditControls, continue_segment_button, "continue_segment_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, delete_segment, "delete_segment");
  GLADE_HOOKUP_OBJECT (ascEditControls, label5, "label5");
  GLADE_HOOKUP_OBJECT (ascEditControls, release_asc_action, "release_asc_action");
  GLADE_HOOKUP_OBJECT (ascEditControls, label10, "label10");
  GLADE_HOOKUP_OBJECT (ascEditControls, label11, "label11");
  GLADE_HOOKUP_OBJECT (ascEditControls, label12, "label12");
  GLADE_HOOKUP_OBJECT (ascEditControls, label13, "label13");
  GLADE_HOOKUP_OBJECT (ascEditControls, label14, "label14");
  GLADE_HOOKUP_OBJECT (ascEditControls, label15, "label15");
  GLADE_HOOKUP_OBJECT (ascEditControls, label16, "label16");
  GLADE_HOOKUP_OBJECT (ascEditControls, select_point, "select_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, recursive_offset_closer_point, "recursive_offset_closer_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, recursive_offset_selected_point, "recursive_offset_selected_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, move_selected_point, "move_selected_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, move_closer_point, "move_closer_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, label17, "label17");
  GLADE_HOOKUP_OBJECT (ascEditControls, label18, "label18");
  GLADE_HOOKUP_OBJECT (ascEditControls, label19, "label19");
  GLADE_HOOKUP_OBJECT (ascEditControls, label20, "label20");
  GLADE_HOOKUP_OBJECT (ascEditControls, label21, "label21");
  GLADE_HOOKUP_OBJECT (ascEditControls, label9, "label9");
  GLADE_HOOKUP_OBJECT (ascEditControls, ascEditor_width, "ascEditor_width");
  GLADE_HOOKUP_OBJECT (ascEditControls, delete_segment_from_point, "delete_segment_from_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, label22, "label22");

  return ascEditControls;
}

GtkWidget*
create_ascSelectShaders (void)
{
  GtkWidget *ascSelectShaders;
  GtkWidget *eventbox1;
  GtkWidget *vbox2;
  GtkWidget *select_filter;

  ascSelectShaders = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascSelectShaders), _("Select shaders"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (ascSelectShaders), eventbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (eventbox1), vbox2);

  select_filter = gtk_combo_box_entry_new_text ();
  gtk_widget_show (select_filter);
  gtk_box_pack_start (GTK_BOX (vbox2), select_filter, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Inversion"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Laplace"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Sobel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Kirsch"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Compass"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Gaussian 3*3"));

  g_signal_connect ((gpointer) select_filter, "changed",
                    G_CALLBACK (on_select_shaders_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascSelectShaders, ascSelectShaders, "ascSelectShaders");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, select_filter, "select_filter");

  return ascSelectShaders;
}

GtkWidget*
create_ascEditControlsSelect (void)
{
  GtkWidget *ascEditControlsSelect;
  AtkObject *atko;
  GtkWidget *table3;
  GtkWidget *label_a;
  GtkWidget *create_selection;
  GtkWidget *label_c;
  GtkWidget *save_selection;
  GtkWidget *label_s;
  GtkWidget *clear_selection;
  GtkWidget *label_e;
  GtkWidget *list_selections;
  GtkWidget *remove_selection;
  GtkWidget *label_r;
  GtkWidget *run_graph_cuts;
  GtkWidget *label_g;
  GtkWidget *selection_type;
  GtkWidget *load_selection;
  GtkWidget *label_l;
  GtkWidget *selection_mode;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *mode_select;
  GtkWidget *mode_point;
  GtkWidget *mode_rect;
  GtkWidget *toggletoolbutton3;
  GtkWidget *hbox2;
  GtkWidget *label23;
  GtkObject *brush_size_adj;
  GtkWidget *brush_size;

  ascEditControlsSelect = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascEditControlsSelect), _("Select tool"));

  table3 = gtk_table_new (13, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (ascEditControlsSelect), table3);

  label_a = gtk_label_new (_("a"));
  gtk_widget_show (label_a);
  gtk_table_attach (GTK_TABLE (table3), label_a, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_a), 0, 0.5);

  create_selection = gtk_button_new_with_mnemonic (_("Create new selection"));
  gtk_widget_show (create_selection);
  gtk_table_attach (GTK_TABLE (table3), create_selection, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_c = gtk_label_new (_("c"));
  gtk_widget_show (label_c);
  gtk_table_attach (GTK_TABLE (table3), label_c, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_c), 0, 0.5);

  save_selection = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_show (save_selection);
  gtk_table_attach (GTK_TABLE (table3), save_selection, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_s = gtk_label_new (_("s"));
  gtk_widget_show (label_s);
  gtk_table_attach (GTK_TABLE (table3), label_s, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_s), 0, 0.5);

  clear_selection = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_show (clear_selection);
  gtk_table_attach (GTK_TABLE (table3), clear_selection, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_e = gtk_label_new (_("e"));
  gtk_widget_show (label_e);
  gtk_table_attach (GTK_TABLE (table3), label_e, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_e), 0, 0.5);

  list_selections = gtk_combo_box_entry_new_text ();
  gtk_widget_show (list_selections);
  gtk_table_attach (GTK_TABLE (table3), list_selections, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  remove_selection = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_show (remove_selection);
  gtk_table_attach (GTK_TABLE (table3), remove_selection, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_r = gtk_label_new (_("r"));
  gtk_widget_show (label_r);
  gtk_table_attach (GTK_TABLE (table3), label_r, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_r), 0, 0.5);

  run_graph_cuts = gtk_button_new_with_mnemonic (_("Run Graph cuts"));
  gtk_widget_show (run_graph_cuts);
  gtk_table_attach (GTK_TABLE (table3), run_graph_cuts, 0, 1, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_g = gtk_label_new (_("g"));
  gtk_widget_show (label_g);
  gtk_table_attach (GTK_TABLE (table3), label_g, 1, 2, 8, 9,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_g), 0, 0.5);

  selection_type = gtk_combo_box_entry_new_text ();
  gtk_widget_show (selection_type);
  gtk_table_attach (GTK_TABLE (table3), selection_type, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (selection_type), _("Simple contour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (selection_type), _("GraphCut"));

  load_selection = gtk_button_new_with_mnemonic (_("Load"));
  gtk_widget_show (load_selection);
  gtk_table_attach (GTK_TABLE (table3), load_selection, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label_l = gtk_label_new (_("l"));
  gtk_widget_show (label_l);
  gtk_table_attach (GTK_TABLE (table3), label_l, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_l), 0, 0.5);

  selection_mode = gtk_toolbar_new ();
  gtk_widget_show (selection_mode);
  gtk_table_attach (GTK_TABLE (table3), selection_mode, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (selection_mode), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (selection_mode));

  mode_select = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_select), _("Select"));
  gtk_widget_show (mode_select);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_select);
  gtk_toggle_tool_button_set_active (GTK_TOGGLE_TOOL_BUTTON (mode_select), TRUE);

  mode_point = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_point), _("Point"));
  gtk_widget_show (mode_point);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_point);

  mode_rect = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_rect), _("Rect"));
  gtk_widget_show (mode_rect);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_rect);

  toggletoolbutton3 = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toggletoolbutton3), "");
  gtk_widget_show (toggletoolbutton3);
  gtk_container_add (GTK_CONTAINER (selection_mode), toggletoolbutton3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table3), hbox2, 0, 1, 9, 10,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label23 = gtk_label_new (_("Brush size"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox2), label23, FALSE, FALSE, 0);

  brush_size_adj = gtk_adjustment_new (0.5, 0, 2, 0.10000000149, 1, 1);
  brush_size = gtk_spin_button_new (GTK_ADJUSTMENT (brush_size_adj), 1, 4);
  gtk_widget_show (brush_size);
  gtk_box_pack_start (GTK_BOX (hbox2), brush_size, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (brush_size), TRUE);

  g_signal_connect ((gpointer) create_selection, "clicked",
                    G_CALLBACK (on_create_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_selection, "clicked",
                    G_CALLBACK (on_save_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear_selection, "clicked",
                    G_CALLBACK (on_clear_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) remove_selection, "clicked",
                    G_CALLBACK (on_remove_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_graph_cuts, "clicked",
                    G_CALLBACK (on_run_graph_cuts_clicked),
                    NULL);
  g_signal_connect ((gpointer) load_selection, "clicked",
                    G_CALLBACK (on_load_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) mode_select, "toggled",
                    G_CALLBACK (on_mode_select_toggled),
                    NULL);
  g_signal_connect ((gpointer) mode_point, "toggled",
                    G_CALLBACK (on_mode_point_toggled),
                    NULL);
  g_signal_connect ((gpointer) mode_rect, "toggled",
                    G_CALLBACK (on_mode_rect_toggled),
                    NULL);

  atko = gtk_widget_get_accessible (ascEditControlsSelect);
  atk_object_set_name (atko, _("Select tools"));


  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascEditControlsSelect, ascEditControlsSelect, "ascEditControlsSelect");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, table3, "table3");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_a, "label_a");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, create_selection, "create_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_c, "label_c");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, save_selection, "save_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_s, "label_s");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, clear_selection, "clear_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_e, "label_e");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, list_selections, "list_selections");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, remove_selection, "remove_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_r, "label_r");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, run_graph_cuts, "run_graph_cuts");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_g, "label_g");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, selection_type, "selection_type");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, load_selection, "load_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_l, "label_l");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, selection_mode, "selection_mode");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_select, "mode_select");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_point, "mode_point");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_rect, "mode_rect");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, toggletoolbutton3, "toggletoolbutton3");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label23, "label23");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, brush_size, "brush_size");

  gtk_widget_grab_default (selection_type);
  return ascEditControlsSelect;
}

