/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GdkPixbuf *main_window_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *alignment2;
  GtkWidget *menubar1;
  GtkWidget *menuitem4;
  GtkWidget *menuitem4_menu;
  GtkWidget *open_stc_file;
  GtkWidget *separatormenuitem1;
  GtkWidget *quit1;
  GtkWidget *menuitem5;
  GtkWidget *menuitem5_menu;
  GtkWidget *screenshot;
  GtkWidget *menuitem6;
  GtkWidget *menuitem6_menu;
  GtkWidget *_3dmenu;
  GtkWidget *xymenu;
  GtkWidget *xzmenu;
  GtkWidget *yzmenu;
  GtkWidget *combomenu;
  GtkWidget *mip1;
  GtkWidget *menu_plugins;
  GtkWidget *menuitem7;
  GtkWidget *menuitem7_menu;
  GtkWidget *about1;
  GtkWidget *hbox1;
  GtkWidget *drawing3D;
  GtkWidget *table1;
  GtkWidget *label2;
  GtkWidget *label1;
  GtkObject *layer_XY_spin_adj;
  GtkWidget *layer_XY_spin;
  GtkWidget *label4;
  GtkObject *cube_row_spin_adj;
  GtkWidget *cube_row_spin;
  GtkWidget *label3;
  GtkObject *cube_col_spin_adj;
  GtkWidget *cube_col_spin;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkObject *layerXZ_spin_adj;
  GtkWidget *layerXZ_spin;
  GtkObject *layer_YZ_spin_adj;
  GtkWidget *layer_YZ_spin;
  GtkWidget *label36;
  GtkWidget *Clear;
  GtkWidget *view_entry;
  GtkWidget *projectionComboBox;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (main_window, 1024, 702);
  gtk_widget_set_events (main_window, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON1_MOTION_MASK | GDK_BUTTON2_MOTION_MASK | GDK_BUTTON3_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_FOCUS_CHANGE_MASK | GDK_STRUCTURE_MASK | GDK_PROPERTY_CHANGE_MASK | GDK_VISIBILITY_NOTIFY_MASK | GDK_PROXIMITY_IN_MASK | GDK_PROXIMITY_OUT_MASK);
  gtk_window_set_title (GTK_WINDOW (main_window), _("VIVA 0.0"));
  main_window_icon_pixbuf = create_pixbuf ("icon.png");
  if (main_window_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (main_window), main_window_icon_pixbuf);
      gdk_pixbuf_unref (main_window_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (main_window), vbox1);
  GTK_WIDGET_SET_FLAGS (vbox1, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (vbox1, GTK_CAN_DEFAULT);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_box_pack_start (GTK_BOX (vbox1), alignment2, FALSE, FALSE, 0);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_container_add (GTK_CONTAINER (alignment2), menubar1);

  menuitem4 = gtk_menu_item_new_with_mnemonic (_("_File"));
  gtk_widget_show (menuitem4);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem4);

  menuitem4_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem4), menuitem4_menu);

  open_stc_file = gtk_menu_item_new_with_mnemonic (_("_Open File"));
  gtk_widget_show (open_stc_file);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), open_stc_file);
  gtk_widget_add_accelerator (open_stc_file, "activate", accel_group,
                              GDK_o, (GdkModifierType) GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  separatormenuitem1 = gtk_separator_menu_item_new ();
  gtk_widget_show (separatormenuitem1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), separatormenuitem1);
  gtk_widget_set_sensitive (separatormenuitem1, FALSE);

  quit1 = gtk_image_menu_item_new_from_stock ("gtk-quit", accel_group);
  gtk_widget_show (quit1);
  gtk_container_add (GTK_CONTAINER (menuitem4_menu), quit1);

  menuitem5 = gtk_menu_item_new_with_mnemonic (_("_Edit"));
  gtk_widget_show (menuitem5);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem5);

  menuitem5_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem5), menuitem5_menu);

  screenshot = gtk_menu_item_new_with_mnemonic (_("Screenshot"));
  gtk_widget_show (screenshot);
  gtk_container_add (GTK_CONTAINER (menuitem5_menu), screenshot);

  menuitem6 = gtk_menu_item_new_with_mnemonic (_("_View"));
  gtk_widget_show (menuitem6);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem6);

  menuitem6_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem6), menuitem6_menu);

  _3dmenu = gtk_menu_item_new_with_mnemonic (_("3_D"));
  gtk_widget_show (_3dmenu);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), _3dmenu);

  xymenu = gtk_menu_item_new_with_mnemonic (_("X_Y"));
  gtk_widget_show (xymenu);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), xymenu);

  xzmenu = gtk_menu_item_new_with_mnemonic (_("X_Z"));
  gtk_widget_show (xzmenu);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), xzmenu);

  yzmenu = gtk_menu_item_new_with_mnemonic (_("Y_Z"));
  gtk_widget_show (yzmenu);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), yzmenu);

  combomenu = gtk_menu_item_new_with_mnemonic (_("_combo"));
  gtk_widget_show (combomenu);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), combomenu);

  mip1 = gtk_menu_item_new_with_mnemonic (_("_MIP"));
  gtk_widget_show (mip1);
  gtk_container_add (GTK_CONTAINER (menuitem6_menu), mip1);

  menu_plugins = gtk_menu_item_new_with_mnemonic (_("_Plugins"));
  gtk_widget_show (menu_plugins);
  gtk_container_add (GTK_CONTAINER (menubar1), menu_plugins);

  menuitem7 = gtk_menu_item_new_with_mnemonic (_("_Help"));
  gtk_widget_show (menuitem7);
  gtk_container_add (GTK_CONTAINER (menubar1), menuitem7);

  menuitem7_menu = gtk_menu_new ();
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (menuitem7), menuitem7_menu);

  about1 = gtk_menu_item_new_with_mnemonic (_("_About"));
  gtk_widget_show (about1);
  gtk_container_add (GTK_CONTAINER (menuitem7_menu), about1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  drawing3D = gtk_drawing_area_new ();
  gtk_widget_show (drawing3D);
  gtk_box_pack_start (GTK_BOX (hbox1), drawing3D, TRUE, TRUE, 0);
  gtk_widget_set_size_request (drawing3D, 800, 600);
  GTK_WIDGET_SET_FLAGS (drawing3D, GTK_CAN_FOCUS);
  GTK_WIDGET_SET_FLAGS (drawing3D, GTK_CAN_DEFAULT);
  gtk_widget_set_events (drawing3D, GDK_EXPOSURE_MASK | GDK_POINTER_MOTION_MASK | GDK_POINTER_MOTION_HINT_MASK | GDK_BUTTON_MOTION_MASK | GDK_BUTTON1_MOTION_MASK | GDK_BUTTON2_MOTION_MASK | GDK_BUTTON3_MOTION_MASK | GDK_BUTTON_PRESS_MASK | GDK_BUTTON_RELEASE_MASK | GDK_KEY_PRESS_MASK | GDK_KEY_RELEASE_MASK | GDK_ENTER_NOTIFY_MASK | GDK_LEAVE_NOTIFY_MASK | GDK_FOCUS_CHANGE_MASK | GDK_STRUCTURE_MASK | GDK_PROPERTY_CHANGE_MASK | GDK_VISIBILITY_NOTIFY_MASK | GDK_PROXIMITY_IN_MASK | GDK_PROXIMITY_OUT_MASK);
  gtk_widget_add_accelerator (drawing3D, "grab-focus", accel_group,
                              GDK_d, (GdkModifierType) 0,
                              GTK_ACCEL_VISIBLE);

  table1 = gtk_table_new (20, 2, TRUE);
  gtk_widget_show (table1);
  gtk_box_pack_end (GTK_BOX (hbox1), table1, FALSE, FALSE, 0);
  gtk_widget_set_size_request (table1, 224, 600);

  label2 = gtk_label_new (_("Layer XY"));
  gtk_widget_show (label2);
  gtk_table_attach (GTK_TABLE (table1), label2, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label1 = gtk_label_new (_("View"));
  gtk_widget_show (label1);
  gtk_table_attach (GTK_TABLE (table1), label1, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  layer_XY_spin_adj = gtk_adjustment_new (1, 0, 500, 1, 10, 10);
  layer_XY_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layer_XY_spin_adj), 1, 0);
  gtk_widget_show (layer_XY_spin);
  gtk_table_attach (GTK_TABLE (table1), layer_XY_spin, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label4 = gtk_label_new (_("Cube Row"));
  gtk_widget_show (label4);
  gtk_table_attach (GTK_TABLE (table1), label4, 0, 1, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cube_row_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  cube_row_spin = gtk_spin_button_new (GTK_ADJUSTMENT (cube_row_spin_adj), 1, 0);
  gtk_widget_show (cube_row_spin);
  gtk_table_attach (GTK_TABLE (table1), cube_row_spin, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label3 = gtk_label_new (_("Cube Col"));
  gtk_widget_show (label3);
  gtk_table_attach (GTK_TABLE (table1), label3, 0, 1, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cube_col_spin_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  cube_col_spin = gtk_spin_button_new (GTK_ADJUSTMENT (cube_col_spin_adj), 1, 0);
  gtk_widget_show (cube_col_spin);
  gtk_table_attach (GTK_TABLE (table1), cube_col_spin, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label7 = gtk_label_new (_("Layer XZ"));
  gtk_widget_show (label7);
  gtk_table_attach (GTK_TABLE (table1), label7, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label8 = gtk_label_new (_("Layer YZ"));
  gtk_widget_show (label8);
  gtk_table_attach (GTK_TABLE (table1), label8, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  layerXZ_spin_adj = gtk_adjustment_new (0, 0, 512, 1, 10, 10);
  layerXZ_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layerXZ_spin_adj), 1, 0);
  gtk_widget_show (layerXZ_spin);
  gtk_table_attach (GTK_TABLE (table1), layerXZ_spin, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  layer_YZ_spin_adj = gtk_adjustment_new (0, 0, 512, 1, 10, 10);
  layer_YZ_spin = gtk_spin_button_new (GTK_ADJUSTMENT (layer_YZ_spin_adj), 1, 0);
  gtk_widget_show (layer_YZ_spin);
  gtk_table_attach (GTK_TABLE (table1), layer_YZ_spin, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label36 = gtk_label_new (_("Projection"));
  gtk_widget_show (label36);
  gtk_table_attach (GTK_TABLE (table1), label36, 0, 1, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label36), 0, 0.5);

  Clear = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_show (Clear);
  gtk_table_attach (GTK_TABLE (table1), Clear, 1, 2, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  view_entry = gtk_combo_box_entry_new_text ();
  gtk_widget_show (view_entry);
  gtk_table_attach (GTK_TABLE (table1), view_entry, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("3D"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("XY"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("XZ"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("YZ"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("Combo"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("MIP"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (view_entry), _("Dual"));
  g_object_set (view_entry, "has_frame", FALSE, NULL);

  projectionComboBox = gtk_combo_box_entry_new_text ();
  gtk_widget_show (projectionComboBox);
  gtk_table_attach (GTK_TABLE (table1), projectionComboBox, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (projectionComboBox), _("MIN"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (projectionComboBox), _("MAX"));

  g_signal_connect ((gpointer) main_window, "destroy",
                    G_CALLBACK (on_ascEditor_destroy),
                    NULL);
  g_signal_connect ((gpointer) main_window, "drag_drop",
                    G_CALLBACK (on_main_window_drag_drop),
                    NULL);
  g_signal_connect ((gpointer) open_stc_file, "activate",
                    G_CALLBACK (on_open_stc_file_activate),
                    NULL);
  g_signal_connect ((gpointer) quit1, "activate",
                    G_CALLBACK (on_quit1_activate),
                    NULL);
  g_signal_connect ((gpointer) screenshot, "activate",
                    G_CALLBACK (on_screenshot_activate),
                    NULL);
  g_signal_connect ((gpointer) _3dmenu, "activate",
                    G_CALLBACK (on_3dmenu_activate),
                    NULL);
  g_signal_connect ((gpointer) xymenu, "activate",
                    G_CALLBACK (on_xymenu_activate),
                    NULL);
  g_signal_connect ((gpointer) xzmenu, "activate",
                    G_CALLBACK (on_xzmenu_activate),
                    NULL);
  g_signal_connect ((gpointer) yzmenu, "activate",
                    G_CALLBACK (on_yzmenu_activate),
                    NULL);
  g_signal_connect ((gpointer) combomenu, "activate",
                    G_CALLBACK (on_combomenu_activate),
                    NULL);
  g_signal_connect ((gpointer) mip1, "activate",
                    G_CALLBACK (on_mip1_activate),
                    NULL);
  g_signal_connect ((gpointer) menu_plugins, "activate",
                    G_CALLBACK (on_menu_plugins_activate),
                    NULL);
  g_signal_connect ((gpointer) about1, "activate",
                    G_CALLBACK (on_about1_activate),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "configure_event",
                    G_CALLBACK (on_drawing3D_configure_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "realize",
                    G_CALLBACK (on_drawing3D_realize),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "expose_event",
                    G_CALLBACK (on_drawing3D_expose_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "button_press_event",
                    G_CALLBACK (on_drawing3D_button_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "motion_notify_event",
                    G_CALLBACK (on_drawing3D_motion_notify_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "drag_drop",
                    G_CALLBACK (on_drawing3D_drag_drop),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "button_release_event",
                    G_CALLBACK (on_drawing3D_button_release_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "drag_data_received",
                    G_CALLBACK (on_drawing3D_drag_data_received),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "key_press_event",
                    G_CALLBACK (on_drawing3D_key_press_event),
                    NULL);
  g_signal_connect ((gpointer) drawing3D, "scroll_event",
                    G_CALLBACK (on_drawing3D_scroll_event),
                    NULL);
  g_signal_connect ((gpointer) layer_XY_spin, "value_changed",
                    G_CALLBACK (on_layer_XY_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) cube_row_spin, "value_changed",
                    G_CALLBACK (on_cube_row_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) cube_col_spin, "value_changed",
                    G_CALLBACK (on_cube_col_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) layerXZ_spin, "value_changed",
                    G_CALLBACK (on_layerXZ_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) layer_YZ_spin, "value_changed",
                    G_CALLBACK (on_layer_YZ_spin_value_changed),
                    NULL);
  g_signal_connect ((gpointer) Clear, "clicked",
                    G_CALLBACK (on_Clear_Stage_clicked),
                    NULL);
  g_signal_connect ((gpointer) view_entry, "changed",
                    G_CALLBACK (on_view_entry_changed),
                    NULL);
  g_signal_connect ((gpointer) projectionComboBox, "changed",
                    G_CALLBACK (on_projectionComboBox_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (main_window, main_window, "main_window");
  GLADE_HOOKUP_OBJECT (main_window, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (main_window, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (main_window, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (main_window, menuitem4, "menuitem4");
  GLADE_HOOKUP_OBJECT (main_window, menuitem4_menu, "menuitem4_menu");
  GLADE_HOOKUP_OBJECT (main_window, open_stc_file, "open_stc_file");
  GLADE_HOOKUP_OBJECT (main_window, separatormenuitem1, "separatormenuitem1");
  GLADE_HOOKUP_OBJECT (main_window, quit1, "quit1");
  GLADE_HOOKUP_OBJECT (main_window, menuitem5, "menuitem5");
  GLADE_HOOKUP_OBJECT (main_window, menuitem5_menu, "menuitem5_menu");
  GLADE_HOOKUP_OBJECT (main_window, screenshot, "screenshot");
  GLADE_HOOKUP_OBJECT (main_window, menuitem6, "menuitem6");
  GLADE_HOOKUP_OBJECT (main_window, menuitem6_menu, "menuitem6_menu");
  GLADE_HOOKUP_OBJECT (main_window, _3dmenu, "_3dmenu");
  GLADE_HOOKUP_OBJECT (main_window, xymenu, "xymenu");
  GLADE_HOOKUP_OBJECT (main_window, xzmenu, "xzmenu");
  GLADE_HOOKUP_OBJECT (main_window, yzmenu, "yzmenu");
  GLADE_HOOKUP_OBJECT (main_window, combomenu, "combomenu");
  GLADE_HOOKUP_OBJECT (main_window, mip1, "mip1");
  GLADE_HOOKUP_OBJECT (main_window, menu_plugins, "menu_plugins");
  GLADE_HOOKUP_OBJECT (main_window, menuitem7, "menuitem7");
  GLADE_HOOKUP_OBJECT (main_window, menuitem7_menu, "menuitem7_menu");
  GLADE_HOOKUP_OBJECT (main_window, about1, "about1");
  GLADE_HOOKUP_OBJECT (main_window, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (main_window, drawing3D, "drawing3D");
  GLADE_HOOKUP_OBJECT (main_window, table1, "table1");
  GLADE_HOOKUP_OBJECT (main_window, label2, "label2");
  GLADE_HOOKUP_OBJECT (main_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (main_window, layer_XY_spin, "layer_XY_spin");
  GLADE_HOOKUP_OBJECT (main_window, label4, "label4");
  GLADE_HOOKUP_OBJECT (main_window, cube_row_spin, "cube_row_spin");
  GLADE_HOOKUP_OBJECT (main_window, label3, "label3");
  GLADE_HOOKUP_OBJECT (main_window, cube_col_spin, "cube_col_spin");
  GLADE_HOOKUP_OBJECT (main_window, label7, "label7");
  GLADE_HOOKUP_OBJECT (main_window, label8, "label8");
  GLADE_HOOKUP_OBJECT (main_window, layerXZ_spin, "layerXZ_spin");
  GLADE_HOOKUP_OBJECT (main_window, layer_YZ_spin, "layer_YZ_spin");
  GLADE_HOOKUP_OBJECT (main_window, label36, "label36");
  GLADE_HOOKUP_OBJECT (main_window, Clear, "Clear");
  GLADE_HOOKUP_OBJECT (main_window, view_entry, "view_entry");
  GLADE_HOOKUP_OBJECT (main_window, projectionComboBox, "projectionComboBox");

  gtk_widget_grab_focus (vbox1);
  gtk_widget_grab_default (vbox1);
  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_ascEditControls (void)
{
  GtkWidget *ascEditControls;
  GtkWidget *table2;
  GtkWidget *new_dendrite_button;
  GtkWidget *branch_button;
  GtkWidget *Erase_Point;
  GtkWidget *continue_segment_button;
  GtkWidget *delete_segment;
  GtkWidget *label5;
  GtkWidget *release_asc_action;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *select_point;
  GtkWidget *recursive_offset_closer_point;
  GtkWidget *recursive_offset_selected_point;
  GtkWidget *move_selected_point;
  GtkWidget *move_closer_point;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label9;
  GtkObject *ascEditor_width_adj;
  GtkWidget *ascEditor_width;
  GtkWidget *delete_segment_from_point;
  GtkWidget *label22;

  ascEditControls = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascEditControls), _("ascEditor"));

  table2 = gtk_table_new (15, 2, FALSE);
  gtk_widget_show (table2);
  gtk_container_add (GTK_CONTAINER (ascEditControls), table2);

  new_dendrite_button = gtk_button_new_with_mnemonic (_("New Dendrite"));
  gtk_widget_show (new_dendrite_button);
  gtk_table_attach (GTK_TABLE (table2), new_dendrite_button, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  branch_button = gtk_button_new_with_mnemonic (_("New Branch"));
  gtk_widget_show (branch_button);
  gtk_table_attach (GTK_TABLE (table2), branch_button, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  Erase_Point = gtk_button_new_with_mnemonic (_("Erase Point"));
  gtk_widget_show (Erase_Point);
  gtk_table_attach (GTK_TABLE (table2), Erase_Point, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  continue_segment_button = gtk_button_new_with_mnemonic (_("Continue Segment"));
  gtk_widget_show (continue_segment_button);
  gtk_table_attach (GTK_TABLE (table2), continue_segment_button, 0, 1, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  delete_segment = gtk_button_new_with_mnemonic (_("Delete Segment"));
  gtk_widget_show (delete_segment);
  gtk_table_attach (GTK_TABLE (table2), delete_segment, 0, 1, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label5 = gtk_label_new (_("ASC Creation"));
  gtk_widget_show (label5);
  gtk_table_attach (GTK_TABLE (table2), label5, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  release_asc_action = gtk_button_new_with_mnemonic (_("noAction"));
  gtk_widget_show (release_asc_action);
  gtk_table_attach (GTK_TABLE (table2), release_asc_action, 0, 1, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label10 = gtk_label_new (_("e"));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table2), label10, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  label11 = gtk_label_new (_("w"));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table2), label11, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  label12 = gtk_label_new (_("r"));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table2), label12, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  label13 = gtk_label_new (_("t"));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table2), label13, 1, 2, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  label14 = gtk_label_new (_("g"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table2), label14, 1, 2, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  label15 = gtk_label_new (_("b\n"));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table2), label15, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Asc Modification"));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table2), label16, 0, 1, 8, 9,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  select_point = gtk_button_new_with_mnemonic (_("Select Point"));
  gtk_widget_show (select_point);
  gtk_table_attach (GTK_TABLE (table2), select_point, 0, 1, 9, 10,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  recursive_offset_closer_point = gtk_button_new_with_mnemonic (_("Recursive Offset Closer Point"));
  gtk_widget_show (recursive_offset_closer_point);
  gtk_table_attach (GTK_TABLE (table2), recursive_offset_closer_point, 0, 1, 13, 14,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  recursive_offset_selected_point = gtk_button_new_with_mnemonic (_("Recursive Offet Selected Point"));
  gtk_widget_show (recursive_offset_selected_point);
  gtk_table_attach (GTK_TABLE (table2), recursive_offset_selected_point, 0, 1, 11, 12,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  move_selected_point = gtk_button_new_with_mnemonic (_("Move Selected Point"));
  gtk_widget_show (move_selected_point);
  gtk_table_attach (GTK_TABLE (table2), move_selected_point, 0, 1, 10, 11,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  move_closer_point = gtk_button_new_with_mnemonic (_("Move Closer Point"));
  gtk_widget_show (move_closer_point);
  gtk_table_attach (GTK_TABLE (table2), move_closer_point, 0, 1, 12, 13,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label17 = gtk_label_new (_("z"));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table2), label17, 1, 2, 9, 10,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("f"));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table2), label18, 1, 2, 10, 11,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("x"));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table2), label19, 1, 2, 11, 12,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  label20 = gtk_label_new (_("v"));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table2), label20, 1, 2, 12, 13,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  label21 = gtk_label_new (_("c"));
  gtk_widget_show (label21);
  gtk_table_attach (GTK_TABLE (table2), label21, 1, 2, 13, 14,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label21), 0, 0.5);

  label9 = gtk_label_new (_("Width"));
  gtk_widget_show (label9);
  gtk_table_attach (GTK_TABLE (table2), label9, 0, 1, 14, 15,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label9), 0, 0.5);

  ascEditor_width_adj = gtk_adjustment_new (0, 0, 100, 1, 10, 10);
  ascEditor_width = gtk_spin_button_new (GTK_ADJUSTMENT (ascEditor_width_adj), 0.25, 0);
  gtk_widget_show (ascEditor_width);
  gtk_table_attach (GTK_TABLE (table2), ascEditor_width, 1, 2, 14, 15,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  delete_segment_from_point = gtk_button_new_with_mnemonic (_("Delete Segment From Point"));
  gtk_widget_show (delete_segment_from_point);
  gtk_table_attach (GTK_TABLE (table2), delete_segment_from_point, 0, 1, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label22 = gtk_label_new (_("h\n"));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table2), label22, 1, 2, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  g_signal_connect ((gpointer) new_dendrite_button, "clicked",
                    G_CALLBACK (on_new_dendrite_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) branch_button, "clicked",
                    G_CALLBACK (on_branch_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) Erase_Point, "clicked",
                    G_CALLBACK (on_Erase_Point_clicked),
                    NULL);
  g_signal_connect ((gpointer) continue_segment_button, "clicked",
                    G_CALLBACK (on_continue_segment_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) delete_segment, "clicked",
                    G_CALLBACK (on_delete_segment_clicked),
                    NULL);
  g_signal_connect ((gpointer) release_asc_action, "clicked",
                    G_CALLBACK (on_release_asc_action_clicked),
                    NULL);
  g_signal_connect ((gpointer) select_point, "clicked",
                    G_CALLBACK (on_select_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) recursive_offset_closer_point, "clicked",
                    G_CALLBACK (on_recursive_offset_closer_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) recursive_offset_selected_point, "clicked",
                    G_CALLBACK (on_recursive_offset_selected_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) move_selected_point, "clicked",
                    G_CALLBACK (on_move_selected_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) move_closer_point, "clicked",
                    G_CALLBACK (on_move_closer_point_clicked),
                    NULL);
  g_signal_connect ((gpointer) ascEditor_width, "value_changed",
                    G_CALLBACK (on_ascEditor_width_value_changed),
                    NULL);
  g_signal_connect ((gpointer) delete_segment_from_point, "clicked",
                    G_CALLBACK (on_delete_segment_from_point_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascEditControls, ascEditControls, "ascEditControls");
  GLADE_HOOKUP_OBJECT (ascEditControls, table2, "table2");
  GLADE_HOOKUP_OBJECT (ascEditControls, new_dendrite_button, "new_dendrite_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, branch_button, "branch_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, Erase_Point, "Erase_Point");
  GLADE_HOOKUP_OBJECT (ascEditControls, continue_segment_button, "continue_segment_button");
  GLADE_HOOKUP_OBJECT (ascEditControls, delete_segment, "delete_segment");
  GLADE_HOOKUP_OBJECT (ascEditControls, label5, "label5");
  GLADE_HOOKUP_OBJECT (ascEditControls, release_asc_action, "release_asc_action");
  GLADE_HOOKUP_OBJECT (ascEditControls, label10, "label10");
  GLADE_HOOKUP_OBJECT (ascEditControls, label11, "label11");
  GLADE_HOOKUP_OBJECT (ascEditControls, label12, "label12");
  GLADE_HOOKUP_OBJECT (ascEditControls, label13, "label13");
  GLADE_HOOKUP_OBJECT (ascEditControls, label14, "label14");
  GLADE_HOOKUP_OBJECT (ascEditControls, label15, "label15");
  GLADE_HOOKUP_OBJECT (ascEditControls, label16, "label16");
  GLADE_HOOKUP_OBJECT (ascEditControls, select_point, "select_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, recursive_offset_closer_point, "recursive_offset_closer_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, recursive_offset_selected_point, "recursive_offset_selected_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, move_selected_point, "move_selected_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, move_closer_point, "move_closer_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, label17, "label17");
  GLADE_HOOKUP_OBJECT (ascEditControls, label18, "label18");
  GLADE_HOOKUP_OBJECT (ascEditControls, label19, "label19");
  GLADE_HOOKUP_OBJECT (ascEditControls, label20, "label20");
  GLADE_HOOKUP_OBJECT (ascEditControls, label21, "label21");
  GLADE_HOOKUP_OBJECT (ascEditControls, label9, "label9");
  GLADE_HOOKUP_OBJECT (ascEditControls, ascEditor_width, "ascEditor_width");
  GLADE_HOOKUP_OBJECT (ascEditControls, delete_segment_from_point, "delete_segment_from_point");
  GLADE_HOOKUP_OBJECT (ascEditControls, label22, "label22");

  return ascEditControls;
}

GtkWidget*
create_ascSelectShaders (void)
{
  GtkWidget *ascSelectShaders;
  GtkWidget *eventbox1;
  GtkWidget *vbox2;
  GtkWidget *select_filter;

  ascSelectShaders = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascSelectShaders), _("Select shaders"));

  eventbox1 = gtk_event_box_new ();
  gtk_widget_show (eventbox1);
  gtk_container_add (GTK_CONTAINER (ascSelectShaders), eventbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (eventbox1), vbox2);

  select_filter = gtk_combo_box_entry_new_text ();
  gtk_widget_show (select_filter);
  gtk_box_pack_start (GTK_BOX (vbox2), select_filter, TRUE, TRUE, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("None"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Inversion"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Laplace"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Sobel"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Kirsch"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Compass"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (select_filter), _("Gaussian 3*3"));

  g_signal_connect ((gpointer) select_filter, "changed",
                    G_CALLBACK (on_select_shaders_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascSelectShaders, ascSelectShaders, "ascSelectShaders");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, eventbox1, "eventbox1");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (ascSelectShaders, select_filter, "select_filter");

  return ascSelectShaders;
}

GtkWidget*
create_ascEditControlsSelect (void)
{
  GtkWidget *ascEditControlsSelect;
  GtkWidget *table3;
  GtkWidget *label_a;
  GtkWidget *create_selection;
  GtkWidget *label_c;
  GtkWidget *save_selection;
  GtkWidget *label_s;
  GtkWidget *clear_selection;
  GtkWidget *label_e;
  GtkWidget *list_selections;
  GtkWidget *remove_selection;
  GtkWidget *label_r;
  GtkWidget *run_graph_cuts;
  GtkWidget *label_g;
  GtkWidget *selection_type;
  GtkWidget *load_selection;
  GtkWidget *label_l;
  GtkWidget *selection_mode;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *mode_select;
  GtkWidget *mode_point;
  GtkWidget *mode_rect;
  GtkWidget *toggletoolbutton3;
  GtkWidget *hbox2;
  GtkWidget *label23;
  GtkObject *brush_size_adj;
  GtkWidget *brush_size;
  GtkWidget *drawing_mode;
  GtkWidget *display_drawings;
  GtkWidget *load_seeds;

  ascEditControlsSelect = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ascEditControlsSelect), _("Select tool"));

  table3 = gtk_table_new (15, 2, FALSE);
  gtk_widget_show (table3);
  gtk_container_add (GTK_CONTAINER (ascEditControlsSelect), table3);

  label_a = gtk_label_new (_("a"));
  gtk_widget_show (label_a);
  gtk_table_attach (GTK_TABLE (table3), label_a, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_a), 0, 0.5);

  create_selection = gtk_button_new_with_mnemonic (_("Create new selection"));
  gtk_widget_show (create_selection);
  gtk_table_attach (GTK_TABLE (table3), create_selection, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_c = gtk_label_new (_("c"));
  gtk_widget_show (label_c);
  gtk_table_attach (GTK_TABLE (table3), label_c, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_c), 0, 0.5);

  save_selection = gtk_button_new_with_mnemonic (_("Save"));
  gtk_widget_show (save_selection);
  gtk_table_attach (GTK_TABLE (table3), save_selection, 0, 1, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_s = gtk_label_new (_("s"));
  gtk_widget_show (label_s);
  gtk_table_attach (GTK_TABLE (table3), label_s, 1, 2, 7, 8,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_s), 0, 0.5);

  clear_selection = gtk_button_new_with_mnemonic (_("Clear"));
  gtk_widget_show (clear_selection);
  gtk_table_attach (GTK_TABLE (table3), clear_selection, 0, 1, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_e = gtk_label_new (_("e"));
  gtk_widget_show (label_e);
  gtk_table_attach (GTK_TABLE (table3), label_e, 1, 2, 5, 6,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_e), 0, 0.5);

  list_selections = gtk_combo_box_entry_new_text ();
  gtk_widget_show (list_selections);
  gtk_table_attach (GTK_TABLE (table3), list_selections, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  remove_selection = gtk_button_new_with_mnemonic (_("Remove"));
  gtk_widget_show (remove_selection);
  gtk_table_attach (GTK_TABLE (table3), remove_selection, 0, 1, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_r = gtk_label_new (_("r"));
  gtk_widget_show (label_r);
  gtk_table_attach (GTK_TABLE (table3), label_r, 1, 2, 6, 7,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_r), 0, 0.5);

  run_graph_cuts = gtk_button_new_with_mnemonic (_("Run Graph cuts"));
  gtk_widget_show (run_graph_cuts);
  gtk_table_attach (GTK_TABLE (table3), run_graph_cuts, 0, 1, 10, 11,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_g = gtk_label_new (_("g"));
  gtk_widget_show (label_g);
  gtk_table_attach (GTK_TABLE (table3), label_g, 1, 2, 10, 11,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_g), 0, 0.5);

  selection_type = gtk_combo_box_entry_new_text ();
  gtk_widget_show (selection_type);
  gtk_table_attach (GTK_TABLE (table3), selection_type, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (selection_type), _("Simple contour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (selection_type), _("GraphCut"));

  load_selection = gtk_button_new_with_mnemonic (_("Load"));
  gtk_widget_show (load_selection);
  gtk_table_attach (GTK_TABLE (table3), load_selection, 0, 1, 8, 9,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label_l = gtk_label_new (_("l"));
  gtk_widget_show (label_l);
  gtk_table_attach (GTK_TABLE (table3), label_l, 1, 2, 8, 9,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label_l), 0, 0.5);

  selection_mode = gtk_toolbar_new ();
  gtk_widget_show (selection_mode);
  gtk_table_attach (GTK_TABLE (table3), selection_mode, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (selection_mode), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (selection_mode));

  mode_select = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_select), _("Select"));
  gtk_widget_show (mode_select);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_select);
  gtk_toggle_tool_button_set_active (GTK_TOGGLE_TOOL_BUTTON (mode_select), TRUE);

  mode_point = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_point), _("Point"));
  gtk_widget_show (mode_point);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_point);

  mode_rect = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (mode_rect), _("Rect"));
  gtk_widget_show (mode_rect);
  gtk_container_add (GTK_CONTAINER (selection_mode), mode_rect);

  toggletoolbutton3 = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (toggletoolbutton3), "");
  gtk_widget_show (toggletoolbutton3);
  gtk_container_add (GTK_CONTAINER (selection_mode), toggletoolbutton3);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_table_attach (GTK_TABLE (table3), hbox2, 0, 1, 11, 12,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  label23 = gtk_label_new (_("Brush size"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox2), label23, FALSE, FALSE, 0);

  brush_size_adj = gtk_adjustment_new (0.5, 0, 10, 0.10000000149, 1, 1);
  brush_size = gtk_spin_button_new (GTK_ADJUSTMENT (brush_size_adj), 1, 3);
  gtk_widget_show (brush_size);
  gtk_box_pack_start (GTK_BOX (hbox2), brush_size, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (brush_size), TRUE);

  drawing_mode = gtk_toolbar_new ();
  gtk_widget_show (drawing_mode);
  gtk_table_attach (GTK_TABLE (table3), drawing_mode, 0, 1, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (drawing_mode), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (drawing_mode));

  display_drawings = (GtkWidget*) gtk_toggle_tool_button_new ();
  gtk_tool_button_set_label (GTK_TOOL_BUTTON (display_drawings), _("Draw"));
  gtk_widget_show (display_drawings);
  gtk_container_add (GTK_CONTAINER (drawing_mode), display_drawings);

  load_seeds = gtk_button_new_with_mnemonic (_("Load seeds"));
  gtk_widget_show (load_seeds);
  gtk_table_attach (GTK_TABLE (table3), load_seeds, 0, 1, 9, 10,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  g_signal_connect ((gpointer) create_selection, "clicked",
                    G_CALLBACK (on_create_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) save_selection, "clicked",
                    G_CALLBACK (on_save_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) clear_selection, "clicked",
                    G_CALLBACK (on_clear_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) remove_selection, "clicked",
                    G_CALLBACK (on_remove_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) run_graph_cuts, "clicked",
                    G_CALLBACK (on_run_graph_cuts_clicked),
                    NULL);
  g_signal_connect ((gpointer) load_selection, "clicked",
                    G_CALLBACK (on_load_selection_clicked),
                    NULL);
  g_signal_connect ((gpointer) mode_select, "toggled",
                    G_CALLBACK (on_mode_select_toggled),
                    NULL);
  g_signal_connect ((gpointer) mode_point, "toggled",
                    G_CALLBACK (on_mode_point_toggled),
                    NULL);
  g_signal_connect ((gpointer) mode_rect, "toggled",
                    G_CALLBACK (on_mode_rect_toggled),
                    NULL);
  g_signal_connect ((gpointer) display_drawings, "toggled",
                    G_CALLBACK (on_display_drawings_toggled),
                    NULL);
  g_signal_connect ((gpointer) load_seeds, "pressed",
                    G_CALLBACK (on_load_seeds_pressed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ascEditControlsSelect, ascEditControlsSelect, "ascEditControlsSelect");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, table3, "table3");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_a, "label_a");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, create_selection, "create_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_c, "label_c");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, save_selection, "save_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_s, "label_s");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, clear_selection, "clear_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_e, "label_e");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, list_selections, "list_selections");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, remove_selection, "remove_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_r, "label_r");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, run_graph_cuts, "run_graph_cuts");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_g, "label_g");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, selection_type, "selection_type");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, load_selection, "load_selection");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label_l, "label_l");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, selection_mode, "selection_mode");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_select, "mode_select");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_point, "mode_point");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, mode_rect, "mode_rect");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, toggletoolbutton3, "toggletoolbutton3");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, label23, "label23");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, brush_size, "brush_size");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, drawing_mode, "drawing_mode");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, display_drawings, "display_drawings");
  GLADE_HOOKUP_OBJECT (ascEditControlsSelect, load_seeds, "load_seeds");

  gtk_widget_grab_default (selection_type);
  return ascEditControlsSelect;
}

GtkWidget*
create_Alpha (void)
{
  GtkWidget *Alpha;
  GtkWidget *table4;
  GtkWidget *label24;
  GtkObject *min_alpha_adj;
  GtkWidget *min_alpha;
  GtkWidget *label25;
  GtkObject *max_alpha_adj;
  GtkWidget *max_alpha;
  GtkWidget *label26;
  GtkWidget *cbBlendFunction;

  Alpha = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Alpha), _("Alpha editor"));

  table4 = gtk_table_new (3, 2, FALSE);
  gtk_widget_show (table4);
  gtk_container_add (GTK_CONTAINER (Alpha), table4);

  label24 = gtk_label_new (_("Min alpha"));
  gtk_widget_show (label24);
  gtk_table_attach (GTK_TABLE (table4), label24, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label24), 0, 0.5);

  min_alpha_adj = gtk_adjustment_new (0, 0, 255, 1, 10, 10);
  min_alpha = gtk_spin_button_new (GTK_ADJUSTMENT (min_alpha_adj), 1, 0);
  gtk_widget_show (min_alpha);
  gtk_table_attach (GTK_TABLE (table4), min_alpha, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label25 = gtk_label_new (_("Max alpha"));
  gtk_widget_show (label25);
  gtk_table_attach (GTK_TABLE (table4), label25, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label25), 0, 0.5);

  max_alpha_adj = gtk_adjustment_new (0, 0, 255, 1, 10, 10);
  max_alpha = gtk_spin_button_new (GTK_ADJUSTMENT (max_alpha_adj), 1, 0);
  gtk_widget_show (max_alpha);
  gtk_table_attach (GTK_TABLE (table4), max_alpha, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label26 = gtk_label_new (_("Blend function"));
  gtk_widget_show (label26);
  gtk_table_attach (GTK_TABLE (table4), label26, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label26), 0, 0.5);

  cbBlendFunction = gtk_combo_box_entry_new_text ();
  gtk_widget_show (cbBlendFunction);
  gtk_table_attach (GTK_TABLE (table4), cbBlendFunction, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbBlendFunction), _("MIN_MAX"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cbBlendFunction), _("ALPHA_TEST"));

  g_signal_connect ((gpointer) min_alpha, "changed",
                    G_CALLBACK (on_min_alpha_changed),
                    NULL);
  g_signal_connect ((gpointer) max_alpha, "changed",
                    G_CALLBACK (on_max_alpha_changed),
                    NULL);
  g_signal_connect ((gpointer) cbBlendFunction, "changed",
                    G_CALLBACK (on_cbBlendFunction_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Alpha, Alpha, "Alpha");
  GLADE_HOOKUP_OBJECT (Alpha, table4, "table4");
  GLADE_HOOKUP_OBJECT (Alpha, label24, "label24");
  GLADE_HOOKUP_OBJECT (Alpha, min_alpha, "min_alpha");
  GLADE_HOOKUP_OBJECT (Alpha, label25, "label25");
  GLADE_HOOKUP_OBJECT (Alpha, max_alpha, "max_alpha");
  GLADE_HOOKUP_OBJECT (Alpha, label26, "label26");
  GLADE_HOOKUP_OBJECT (Alpha, cbBlendFunction, "cbBlendFunction");

  return Alpha;
}

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *table5;
  GtkWidget *draw_neuron;
  GtkWidget *draw_cube_toggle;
  GtkWidget *get_matrix_button;
  GtkWidget *shaders;
  GtkWidget *cube_transparency;
  GtkWidget *buttonViewOnlyCube;
  GtkWidget *label6;
  GtkObject *layer_view_adj;
  GtkWidget *layer_view;
  GtkWidget *open_4d_stack1;
  GtkWidget *videolayers;
  GtkWidget *videorotation;
  GtkWidget *videorotationtime;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  table5 = gtk_table_new (5, 5, FALSE);
  gtk_widget_show (table5);
  gtk_container_add (GTK_CONTAINER (window1), table5);

  draw_neuron = gtk_toggle_button_new_with_mnemonic (_("Draw Neuron"));
  gtk_widget_show (draw_neuron);
  gtk_table_attach (GTK_TABLE (table5), draw_neuron, 0, 1, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  draw_cube_toggle = gtk_toggle_button_new_with_mnemonic (_("Draw Cube"));
  gtk_widget_show (draw_cube_toggle);
  gtk_table_attach (GTK_TABLE (table5), draw_cube_toggle, 0, 1, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  get_matrix_button = gtk_button_new_with_mnemonic (_("Get_Matrix"));
  gtk_widget_show (get_matrix_button);
  gtk_table_attach (GTK_TABLE (table5), get_matrix_button, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  shaders = gtk_button_new_with_mnemonic (_("Shaders"));
  gtk_widget_show (shaders);
  gtk_table_attach (GTK_TABLE (table5), shaders, 1, 2, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  cube_transparency = gtk_toggle_button_new_with_mnemonic (_("Cube Transparency"));
  gtk_widget_show (cube_transparency);
  gtk_table_attach (GTK_TABLE (table5), cube_transparency, 1, 2, 1, 2,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  buttonViewOnlyCube = gtk_toggle_button_new_with_mnemonic (_("OnlyCube"));
  gtk_widget_show (buttonViewOnlyCube);
  gtk_table_attach (GTK_TABLE (table5), buttonViewOnlyCube, 1, 2, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  label6 = gtk_label_new (_("LayerSpanViewZ"));
  gtk_widget_show (label6);
  gtk_table_attach (GTK_TABLE (table5), label6, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label6), 0, 0.5);

  layer_view_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  layer_view = gtk_spin_button_new (GTK_ADJUSTMENT (layer_view_adj), 1, 0);
  gtk_widget_show (layer_view);
  gtk_table_attach (GTK_TABLE (table5), layer_view, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  open_4d_stack1 = gtk_menu_item_new_with_mnemonic (_("Open 4D stack"));
  gtk_widget_show (open_4d_stack1);
  gtk_table_attach (GTK_TABLE (table5), open_4d_stack1, 2, 3, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  videolayers = gtk_menu_item_new_with_mnemonic (_("VideoLayers"));
  gtk_widget_show (videolayers);
  gtk_table_attach (GTK_TABLE (table5), videolayers, 1, 2, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  videorotation = gtk_menu_item_new_with_mnemonic (_("VIdeoRotation"));
  gtk_widget_show (videorotation);
  gtk_table_attach (GTK_TABLE (table5), videorotation, 0, 1, 3, 4,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);

  videorotationtime = gtk_menu_item_new_with_mnemonic (_("VideoRotationTime"));
  gtk_widget_show (videorotationtime);
  gtk_table_attach (GTK_TABLE (table5), videorotationtime, 0, 1, 4, 5,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);

  g_signal_connect ((gpointer) draw_neuron, "toggled",
                    G_CALLBACK (on_draw_neuron_toggled),
                    NULL);
  g_signal_connect ((gpointer) draw_cube_toggle, "toggled",
                    G_CALLBACK (on_draw_cube_toggle_toggled),
                    NULL);
  g_signal_connect ((gpointer) get_matrix_button, "clicked",
                    G_CALLBACK (on_get_matrix_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) shaders, "clicked",
                    G_CALLBACK (on_shaders_clicked),
                    NULL);
  g_signal_connect ((gpointer) cube_transparency, "toggled",
                    G_CALLBACK (on_cube_transparency_toggled),
                    NULL);
  g_signal_connect ((gpointer) buttonViewOnlyCube, "toggled",
                    G_CALLBACK (on_buttonViewOnlyCube_toggled),
                    NULL);
  g_signal_connect ((gpointer) layer_view, "value_changed",
                    G_CALLBACK (on_layer_view_value_changed),
                    NULL);
  g_signal_connect ((gpointer) open_4d_stack1, "activate",
                    G_CALLBACK (on_open_4d_stack1_activate),
                    NULL);
  g_signal_connect ((gpointer) videolayers, "activate",
                    G_CALLBACK (on_videolayers_activate),
                    NULL);
  g_signal_connect ((gpointer) videorotation, "activate",
                    G_CALLBACK (on_videorotation_activate),
                    NULL);
  g_signal_connect ((gpointer) videorotationtime, "activate",
                    G_CALLBACK (on_videorotationtime_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, table5, "table5");
  GLADE_HOOKUP_OBJECT (window1, draw_neuron, "draw_neuron");
  GLADE_HOOKUP_OBJECT (window1, draw_cube_toggle, "draw_cube_toggle");
  GLADE_HOOKUP_OBJECT (window1, get_matrix_button, "get_matrix_button");
  GLADE_HOOKUP_OBJECT (window1, shaders, "shaders");
  GLADE_HOOKUP_OBJECT (window1, cube_transparency, "cube_transparency");
  GLADE_HOOKUP_OBJECT (window1, buttonViewOnlyCube, "buttonViewOnlyCube");
  GLADE_HOOKUP_OBJECT (window1, label6, "label6");
  GLADE_HOOKUP_OBJECT (window1, layer_view, "layer_view");
  GLADE_HOOKUP_OBJECT (window1, open_4d_stack1, "open_4d_stack1");
  GLADE_HOOKUP_OBJECT (window1, videolayers, "videolayers");
  GLADE_HOOKUP_OBJECT (window1, videorotation, "videorotation");
  GLADE_HOOKUP_OBJECT (window1, videorotationtime, "videorotationtime");

  return window1;
}

GtkWidget*
create_About (void)
{
  GtkWidget *About;
  GtkWidget *label27;

  About = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (About), _("VIVA"));

  label27 = gtk_label_new (_("German Gonzalez <german.gonzalez@epfl.ch>\nKevin Smith < kevin.smith@epfl.ch >\nAurelien Lucchi <aurelien.lucchi@epfl.ch >"));
  gtk_widget_show (label27);
  gtk_container_add (GTK_CONTAINER (About), label27);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (About, About, "About");
  GLADE_HOOKUP_OBJECT (About, label27, "label27");

  return About;
}

GtkWidget*
create_loadImageStack (void)
{
  GtkWidget *loadImageStack;
  GtkWidget *vbox3;
  GtkWidget *hbox3;
  GtkWidget *label28;
  GtkWidget *entry_3DLIS_D;
  GtkWidget *_3DLIS_CDir;
  GtkWidget *image3;
  GtkWidget *hbox4;
  GtkWidget *label29;
  GtkWidget *_3DLIS_FF;
  GtkWidget *hbox5;
  GtkWidget *label30;
  GtkObject *_3DLIS_SBI_adj;
  GtkWidget *_3DLIS_SBI;
  GtkWidget *label31;
  GtkObject *_3DLIS_SE_adj;
  GtkWidget *_3DLIS_SE;
  GtkWidget *hbox6;
  GtkWidget *label32;
  GtkObject *_3DISL_VW_adj;
  GtkWidget *_3DISL_VW;
  GtkWidget *label33;
  GtkObject *_3DISL_VH_adj;
  GtkWidget *_3DISL_VH;
  GtkWidget *label34;
  GtkObject *_3DISL_VD_adj;
  GtkWidget *_3DISL_VD;
  GtkWidget *hbox9;
  GtkWidget *_3DLIS_saveStackB;
  GtkWidget *_3DLIS_saveStackText;
  GtkWidget *_3DLIS_saveStackDialogB;
  GtkWidget *_3DLIS_saveStack_BB;
  GtkWidget *alignment1;
  GtkWidget *hbox10;
  GtkWidget *image4;
  GtkWidget *label35;
  GtkWidget *hbox8;
  GtkWidget *_3DIS_OK;
  GtkWidget *_3DLIS_C;

  loadImageStack = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (loadImageStack), _("3D Image Stack"));

  vbox3 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox3);
  gtk_container_add (GTK_CONTAINER (loadImageStack), vbox3);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox3, TRUE, TRUE, 0);

  label28 = gtk_label_new (_("Directory:   "));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox3), label28, FALSE, FALSE, 0);

  entry_3DLIS_D = gtk_entry_new ();
  gtk_widget_show (entry_3DLIS_D);
  gtk_box_pack_start (GTK_BOX (hbox3), entry_3DLIS_D, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_3DLIS_D), 9679);

  _3DLIS_CDir = gtk_button_new ();
  gtk_widget_show (_3DLIS_CDir);
  gtk_box_pack_start (GTK_BOX (hbox3), _3DLIS_CDir, FALSE, FALSE, 0);

  image3 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_container_add (GTK_CONTAINER (_3DLIS_CDir), image3);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox4, TRUE, TRUE, 0);

  label29 = gtk_label_new (_("File Format: "));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox4), label29, FALSE, FALSE, 0);

  _3DLIS_FF = gtk_entry_new ();
  gtk_widget_show (_3DLIS_FF);
  gtk_box_pack_start (GTK_BOX (hbox4), _3DLIS_FF, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (_3DLIS_FF), 9679);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox5, TRUE, TRUE, 0);

  label30 = gtk_label_new (_("Z Init"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox5), label30, FALSE, FALSE, 0);

  _3DLIS_SBI_adj = gtk_adjustment_new (1, 0, 100, 1, 10, 10);
  _3DLIS_SBI = gtk_spin_button_new (GTK_ADJUSTMENT (_3DLIS_SBI_adj), 1, 0);
  gtk_widget_show (_3DLIS_SBI);
  gtk_box_pack_start (GTK_BOX (hbox5), _3DLIS_SBI, TRUE, TRUE, 0);

  label31 = gtk_label_new (_("Z End"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox5), label31, FALSE, FALSE, 0);

  _3DLIS_SE_adj = gtk_adjustment_new (30, 0, 100, 1, 10, 10);
  _3DLIS_SE = gtk_spin_button_new (GTK_ADJUSTMENT (_3DLIS_SE_adj), 1, 0);
  gtk_widget_show (_3DLIS_SE);
  gtk_box_pack_start (GTK_BOX (hbox5), _3DLIS_SE, TRUE, TRUE, 0);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox6, TRUE, TRUE, 0);

  label32 = gtk_label_new (_("Voxel\nWidth"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox6), label32, FALSE, FALSE, 0);

  _3DISL_VW_adj = gtk_adjustment_new (1, 0, 100, 0.10000000149, 1, 10);
  _3DISL_VW = gtk_spin_button_new (GTK_ADJUSTMENT (_3DISL_VW_adj), 1, 2);
  gtk_widget_show (_3DISL_VW);
  gtk_box_pack_start (GTK_BOX (hbox6), _3DISL_VW, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (_3DISL_VW), TRUE);

  label33 = gtk_label_new (_("Voxel\nHeight"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox6), label33, FALSE, FALSE, 0);

  _3DISL_VH_adj = gtk_adjustment_new (1, 0, 100, 0.10000000149, 1, 10);
  _3DISL_VH = gtk_spin_button_new (GTK_ADJUSTMENT (_3DISL_VH_adj), 1, 2);
  gtk_widget_show (_3DISL_VH);
  gtk_box_pack_start (GTK_BOX (hbox6), _3DISL_VH, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (_3DISL_VH), TRUE);

  label34 = gtk_label_new (_("Voxel\nDepth"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox6), label34, FALSE, FALSE, 0);

  _3DISL_VD_adj = gtk_adjustment_new (1, 0, 100, 0.10000000149, 10, 10);
  _3DISL_VD = gtk_spin_button_new (GTK_ADJUSTMENT (_3DISL_VD_adj), 1, 2);
  gtk_widget_show (_3DISL_VD);
  gtk_box_pack_start (GTK_BOX (hbox6), _3DISL_VD, TRUE, TRUE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (_3DISL_VD), TRUE);

  hbox9 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox9, TRUE, TRUE, 0);

  _3DLIS_saveStackB = gtk_check_button_new_with_mnemonic (_("Save Stack"));
  gtk_widget_show (_3DLIS_saveStackB);
  gtk_box_pack_start (GTK_BOX (hbox9), _3DLIS_saveStackB, FALSE, FALSE, 0);

  _3DLIS_saveStackText = gtk_entry_new ();
  gtk_widget_show (_3DLIS_saveStackText);
  gtk_box_pack_start (GTK_BOX (hbox9), _3DLIS_saveStackText, TRUE, TRUE, 0);
  gtk_entry_set_invisible_char (GTK_ENTRY (_3DLIS_saveStackText), 9679);

  _3DLIS_saveStackDialogB = gtk_button_new ();
  gtk_widget_show (_3DLIS_saveStackDialogB);
  gtk_box_pack_start (GTK_BOX (hbox9), _3DLIS_saveStackDialogB, FALSE, FALSE, 0);

  _3DLIS_saveStack_BB = gtk_button_new ();
  gtk_widget_show (_3DLIS_saveStack_BB);
  gtk_container_add (GTK_CONTAINER (_3DLIS_saveStackDialogB), _3DLIS_saveStack_BB);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (_3DLIS_saveStack_BB), alignment1);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox10);

  image4 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox10), image4, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("b"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox10), label35, FALSE, FALSE, 0);

  hbox8 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox8, TRUE, TRUE, 0);

  _3DIS_OK = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (_3DIS_OK);
  gtk_box_pack_start (GTK_BOX (hbox8), _3DIS_OK, TRUE, TRUE, 0);

  _3DLIS_C = gtk_button_new_with_mnemonic (_("Cancel"));
  gtk_widget_show (_3DLIS_C);
  gtk_box_pack_start (GTK_BOX (hbox8), _3DLIS_C, FALSE, TRUE, 0);

  g_signal_connect ((gpointer) entry_3DLIS_D, "changed",
                    G_CALLBACK (on_3DLIS_D_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_CDir, "clicked",
                    G_CALLBACK (on_3DLIS_CDir_clicked),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_FF, "changed",
                    G_CALLBACK (on_3DLIS_FF_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_SBI, "value_changed",
                    G_CALLBACK (on_3DLIS_SBI_value_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_SE, "value_changed",
                    G_CALLBACK (on_3DLIS_SE_value_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DISL_VW, "value_changed",
                    G_CALLBACK (on_3DISL_VW_value_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DISL_VH, "value_changed",
                    G_CALLBACK (on_3DISL_VH_value_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DISL_VD, "value_changed",
                    G_CALLBACK (on_3DISL_VD_value_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_saveStackB, "toggled",
                    G_CALLBACK (on__3DLIS_saveStackB_toggled),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_saveStackText, "changed",
                    G_CALLBACK (on__3DLIS_saveStackText_changed),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_saveStack_BB, "clicked",
                    G_CALLBACK (on__3DLIS_saveStack_BB_clicked),
                    NULL);
  g_signal_connect ((gpointer) _3DIS_OK, "clicked",
                    G_CALLBACK (on_3DIS_OK_clicked),
                    NULL);
  g_signal_connect ((gpointer) _3DLIS_C, "clicked",
                    G_CALLBACK (on_3DLIS_C_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (loadImageStack, loadImageStack, "loadImageStack");
  GLADE_HOOKUP_OBJECT (loadImageStack, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (loadImageStack, label28, "label28");
  GLADE_HOOKUP_OBJECT (loadImageStack, entry_3DLIS_D, "entry_3DLIS_D");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_CDir, "_3DLIS_CDir");
  GLADE_HOOKUP_OBJECT (loadImageStack, image3, "image3");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (loadImageStack, label29, "label29");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_FF, "_3DLIS_FF");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (loadImageStack, label30, "label30");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_SBI, "_3DLIS_SBI");
  GLADE_HOOKUP_OBJECT (loadImageStack, label31, "label31");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_SE, "_3DLIS_SE");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (loadImageStack, label32, "label32");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DISL_VW, "_3DISL_VW");
  GLADE_HOOKUP_OBJECT (loadImageStack, label33, "label33");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DISL_VH, "_3DISL_VH");
  GLADE_HOOKUP_OBJECT (loadImageStack, label34, "label34");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DISL_VD, "_3DISL_VD");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_saveStackB, "_3DLIS_saveStackB");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_saveStackText, "_3DLIS_saveStackText");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_saveStackDialogB, "_3DLIS_saveStackDialogB");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_saveStack_BB, "_3DLIS_saveStack_BB");
  GLADE_HOOKUP_OBJECT (loadImageStack, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (loadImageStack, image4, "image4");
  GLADE_HOOKUP_OBJECT (loadImageStack, label35, "label35");
  GLADE_HOOKUP_OBJECT (loadImageStack, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DIS_OK, "_3DIS_OK");
  GLADE_HOOKUP_OBJECT (loadImageStack, _3DLIS_C, "_3DLIS_C");

  return loadImageStack;
}

GtkWidget*
create_filechooserdialog1 (void)
{
  GtkWidget *filechooserdialog1;
  GtkWidget *dialog_vbox1;
  GtkWidget *dialog_action_area1;
  GtkWidget *button1;
  GtkWidget *button2;

  filechooserdialog1 = gtk_file_chooser_dialog_new ("", NULL, GTK_FILE_CHOOSER_ACTION_OPEN, NULL);
  gtk_container_set_border_width (GTK_CONTAINER (filechooserdialog1), 5);
  gtk_window_set_type_hint (GTK_WINDOW (filechooserdialog1), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox1 = GTK_DIALOG (filechooserdialog1)->vbox;
  gtk_widget_show (dialog_vbox1);

  dialog_action_area1 = GTK_DIALOG (filechooserdialog1)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  button1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (button1);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  button2 = gtk_button_new_from_stock ("gtk-open");
  gtk_widget_show (button2);
  gtk_dialog_add_action_widget (GTK_DIALOG (filechooserdialog1), button2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, filechooserdialog1, "filechooserdialog1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT_NO_REF (filechooserdialog1, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button1, "button1");
  GLADE_HOOKUP_OBJECT (filechooserdialog1, button2, "button2");

  gtk_widget_grab_default (button2);
  return filechooserdialog1;
}

