/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_main_window (void);
GtkWidget* create_ascEditControls (void);
GtkWidget* create_ascSelectShaders (void);
GtkWidget* create_ascEditControlsSelect (void);
GtkWidget* create_Alpha (void);
GtkWidget* create_window1 (void);
GtkWidget* create_About (void);
GtkWidget* create_loadImageStack (void);
GtkWidget* create_filechooserdialog1 (void);
