

# Add source files here
EXECUTABLE	:= cubeSteerM
# CUDA source files (compiled with cudacc)
CUFILES		:= ../cubeHessian/convolutionSeparable3D.cu rtf3D.cu
# CUDA dependency files
CU_DEPS		:= GPUcommon.h
# C/C++ source files (compiled with gcc / c++)
CCFILES		:= main.cpp GPUfunctions.cpp

#convolutionSeparable_gold.cp


################################################################################
# Rules and targets

include ../../common/common.mk
